### ISSUE TITLE
Does not run after upgrading HA to 2023.6

### ISSUE THREAD

**Issue by Hoekeren** [Miicroo/ha-birthdays#10]
The integration does not run after upgrading HA to 2023.6

**Comment by SLG** [comment]
This is the related logline:
```
Error during setup of component birthdays
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 283, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/birthdays/__init__.py", line 46, in async_setup
    await asyncio.wait(tasks)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

**Comment by modern74** [comment]
I have the same problem.....

**Comment by lotooo** [comment]
I opened https://github.com/Miicroo/ha-birthdays/pull/11 as a possible fix

**Comment by mspinolo** [comment]
Same issue for me

**Comment by Miicroo** [comment]
#11 merged and verified working! 👍 Thanks @lotooo for the fix
